FROM localhost/sleses8_shim_review
COPY shim-unsigned-x64-16.1-2.el8.src.rpm /
RUN rpm --define '_topdir /var/tmp/build-shim-unsigned-x64-16.1-2.el8.src.rpm' -ivh /shim-unsigned-x64-16.1-2.el8.src.rpm
RUN sed -i 's/linux32 -B/linux32/g' /var/tmp/build-shim-unsigned-x64-16.1-2.el8.src.rpm/SPECS/shim-unsigned-x64.spec
RUN rpmbuild --define '_topdir /var/tmp/build-shim-unsigned-x64-16.1-2.el8.src.rpm' -ba /var/tmp/build-shim-unsigned-x64-16.1-2.el8.src.rpm/SPECS/shim-unsigned-x64.spec
COPY shim*.efi /
#COPY shimx64.efi /
#COPY shimia32.nx.efi /
#COPY shimx64.nx.efi /

RUN ls -la /var/tmp/build-shim-unsigned-x64-16.1-2.el8.src.rpm/RPMS/x86_64/
RUN rpm2cpio /var/tmp/build-shim-unsigned-x64-16.1-2.el8.src.rpm/RPMS/x86_64/shim-unsigned-ia32-16.1-2.el8.x86_64.rpm  | cpio -diu
RUN rpm2cpio /var/tmp/build-shim-unsigned-x64-16.1-2.el8.src.rpm/RPMS/x86_64/shim-unsigned-x64-16.1-2.el8.x86_64.rpm | cpio -diu
RUN ls -l /*.efi ./usr/share/shim/16.1-2.el8/*/shim*.efi

RUN sha256sum ./usr/share/shim/16.1-2.el8/x64/shimx64.efi ./usr/share/shim/16.1-2.el8/ia32/shimia32.efi ./usr/share/shim/16.1-2.el8/x64/shimx64.nx.efi ./usr/share/shim/16.1-2.el8/ia32/shimia32.nx.efi /shimia32.efi /shimx64.efi /shimia32.nx.efi /shimx64.nx.efi

#noNX
RUN hexdump -Cv ./usr/share/shim/16.1-2.el8/x64/shimx64.efi > built-x64.hex
RUN hexdump -Cv ./usr/share/shim/16.1-2.el8/ia32/shimia32.efi > built-ia32.hex
RUN hexdump -Cv /shimia32.efi > orig-ia32.hex
RUN hexdump -Cv /shimx64.efi > orig-x64.hex
#NX
RUN hexdump -Cv ./usr/share/shim/16.1-2.el8/x64/shimx64.nx.efi > built-x64.nx.hex
RUN hexdump -Cv ./usr/share/shim/16.1-2.el8/ia32/shimia32.nx.efi > built-ia32.nx.hex
RUN hexdump -Cv /shimia32.nx.efi > orig-ia32.nx.hex
RUN hexdump -Cv /shimx64.nx.efi > orig-x64.nx.hex
#noNX
RUN objdump -h /usr/share/shim/16.1-2.el8/x64/shimx64.efi
RUN objdump -h /usr/share/shim/16.1-2.el8/ia32/shimia32.efi
RUN diff -u orig-ia32.hex built-ia32.hex
RUN diff -u orig-x64.hex built-x64.hex
#NX
RUN objdump -h /usr/share/shim/16.1-2.el8/x64/shimx64.nx.efi
RUN objdump -h /usr/share/shim/16.1-2.el8/ia32/shimia32.nx.efi
RUN diff -u orig-ia32.nx.hex built-ia32.nx.hex
RUN diff -u orig-x64.nx.hex built-x64.nx.hex
#noNX
RUN cmp ./usr/share/shim/16.1-2.el8/x64/shimx64.efi /shimx64.efi
RUN cmp ./usr/share/shim/16.1-2.el8/ia32/shimia32.efi /shimia32.efi
#NX
RUN cmp ./usr/share/shim/16.1-2.el8/x64/shimx64.nx.efi /shimx64.nx.efi
RUN cmp ./usr/share/shim/16.1-2.el8/ia32/shimia32.nx.efi /shimia32.nx.efi
#noNX
RUN pesign -h -P -i /usr/share/shim/16.1-2.el8/ia32/shimia32.efi
RUN pesign -h -P -i /shimia32.efi
RUN pesign -h -P -i /usr/share/shim/16.1-2.el8/x64/shimx64.efi
RUN pesign -h -P -i /shimx64.efi
#NX
RUN pesign -h -P -i /usr/share/shim/16.1-2.el8/ia32/shimia32.nx.efi
RUN pesign -h -P -i /shimia32.nx.efi
RUN pesign -h -P -i /usr/share/shim/16.1-2.el8/x64/shimx64.nx.efi
RUN pesign -h -P -i /shimx64.nx.efi

RUN sha256sum ./usr/share/shim/16.1-2.el8/x64/shimx64.efi /shimx64.efi ./usr/share/shim/16.1-2.el8/ia32/shimia32.efi /shimia32.efi ./usr/share/shim/16.1-2.el8/x64/shimx64.nx.efi /shimx64.nx.efi ./usr/share/shim/16.1-2.el8/ia32/shimia32.nx.efi /shimia32.nx.efi 

